all: cs241 ece222 psych101 se212 stat206


.PHONY: cs241
cs241:
	make -C cs241

.PHONY: ece222
ece222:
	make -C ece222

.PHONY: psych101
psych101:
	make -C psych101

.PHONY: se212
se212:
	make -C se212

.PHONY: stat206
stat206:
	make -C stat206


clean:
	make -C cs241 clean
	make -C ece222 clean
	make -C psych101 clean
	make -C se212 clean
	make -C stat206 clean
