all: cs241 ece222 psych101 se212 stat206


cs241:
	make -C cs241

ece222:
	make -C ece222

psych101:
	make -C psych101

se212:
	make -C se212

stat206:
	make -C stat206


clean:
	make -C cs241 clean
	make -C ece222 clean
	make -C psych101 clean
	make -C se212 clean
	make -C stat206 clean


.PHONY: cs241 ece222 psych101 se212 stat206
