all: cs240 cs247 engl119 math213 math239 msci261


cs240:
	make -C cs240

cs247:
	make -C cs247

engl119:
	make -C engl119

math213:
	make -C math213

math239:
	make -C math239

msci261:
	make -C msci261


clean:
	make -C cs240 clean
	make -C cs247 clean
	make -C engl119 clean
	make -C math213 clean
	make -C math239 clean
	make -C msci261 clean


.PHONY: cs240 cs247 engl119 math213 math239 msci261
