version: 2.1

orbs:
  linter: talkiq/linter@4.0.0

executors:
  python:
    docker:
      - image: python:3.14.0
    resource_class: medium
  xelatex:
    docker:
      - image: moss/xelatex:1.3.3
    resource_class: medium

commands:
  fetch-tex:
    parameters:
      path:
        default: 'macros/latex/contrib'
        type: string
      pkg:
        type: string
      url:
        default: 'https://mirrors.rit.edu/CTAN/'
        # default: 'https://mirror.ctan.org'
        type: string
    steps:
      - run: curl -LsS <<parameters.url>>/<<parameters.path>>/<<parameters.pkg>>.zip > /tmp.zip
      - run: unzip /tmp.zip -d $(kpsewhich --var-value TEXMFLOCAL)

jobs:
  build-curse-of-strahd:
    executor: xelatex
    steps:
      - run: apt-get update -qy
      - run: apt-get install -qy curl zip
      - fetch-tex:
          path: 'fonts/aurical'
          pkg: aurical_texmf
      - run: texhash
      - checkout
      - run:
          command: xelatex journal.tex
          working_directory: curse-of-strahd
      - run: mkdir -p build/
      - run: mv curse-of-strahd/journal.pdf build/curse-of-strahd.pdf
      - persist_to_workspace:
          root: build
          paths:
            - curse-of-strahd.pdf
      - store_artifacts:
          path: build/curse-of-strahd.pdf

  build-notes:
    executor: xelatex
    steps:
      - run: apt-get update -qy
      - run: apt-get install -qy curl zip
      - fetch-tex:
          pkg: booktabs
      - fetch-tex:
          pkg: listings
      - fetch-tex:
          pkg: mathtools
      - fetch-tex:
          pkg: parskip
      - fetch-tex:
          pkg: pict2e
      - fetch-tex:
          pkg: qtree
      - run: mkdir -p ~/texmf/tex/latex/
      - run: cp -r $(kpsewhich --var-value TEXMFLOCAL)/qtree ~/texmf/tex/latex/
      - fetch-tex:
          pkg: ulem
      - fetch-tex:
          pkg: url
      - fetch-tex:
          pkg: wrapfig
      - run: texhash
      - checkout
      - run:
          name: install custom.sty
          command: |
            mkdir -p ~/texmf/tex/latex/custom
            cp notes-uwaterloo/custom.sty ~/texmf/tex/latex/custom/custom.sty
            texhash
      - run: mkdir -p build/
      - run:
          name: make
          command: |
            make -j2
            find . -name '*.pdf' | xargs -I{} mv {} ../build
          working_directory: notes-uwaterloo
      - store_artifacts:
          path: build/

  upload:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gsutil -m cp build/curse-of-strahd.pdf gs://thekevjames-artifacts

workflows:
  build:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - linter/pre-commit:
          executor: python
      - build-curse-of-strahd
      - build-notes

  upload:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - linter/pre-commit:
          executor: python
      - build-curse-of-strahd
      - build-notes
      - upload:
          requires:
            - build-curse-of-strahd
