all: cs138 ece106 ece124 math119 math135


.PHONY: cs138
cs138:
	make -C cs138

.PHONY: ece106
ece106:
	make -C ece106

.PHONY: ece124
ece124:
	make -C ece124

.PHONY: math119
math119:
	make -C math119

.PHONY: math135
math135:
	make -C math135


clean:
	make -C cs138 clean
	make -C ece106 clean
	make -C ece124 clean
	make -C math119 clean
	make -C math135 clean
