all: cs138 ece106 ece124 math119 math135


cs138:
	make -C cs138

ece106:
	make -C ece106

ece124:
	make -C ece124

math119:
	make -C math119

math135:
	make -C math135


clean:
	make -C cs138 clean
	make -C ece106 clean
	make -C ece124 clean
	make -C math119 clean
	make -C math135 clean


.PHONY: cs138 ece106 ece124 math119 math135
