include ../../latex.Makefile


all: ece140.pdf
ece140.pdf: ece140.tex differenceamp.png impedance.png invertingamp.png noninvertingamp.png opamp.png opampforms.png samplecircuit.png samplecircuitsolved.png summingamp.png

clean:
	rm -f ece140.pdf
