all: cs137 ece105 ece140 math115 math117 se101


cs137:
	make -C cs137

ece105:
	make -C ece105

ece140:
	make -C ece140

math115:
	make -C math115

math117:
	make -C math117

se101:
	make -C se101


clean:
	make -C cs137 clean
	make -C ece105 clean
	make -C ece140 clean
	make -C math115 clean
	make -C math117 clean
	make -C se101 clean


.PHONY: cs137 ece105 ece140 math115 math117 se101
