all: cs137 ece105 ece140 math115 math117 se101


.PHONY: cs137
cs137:
	make -C cs137

.PHONY: ece105
ece105:
	make -C ece105

.PHONY: ece140
ece140:
	make -C ece140

.PHONY: math115
math115:
	make -C math115

.PHONY: math117
math117:
	make -C math117

.PHONY: se101
se101:
	make -C se101


clean:
	make -C cs137 clean
	make -C ece105 clean
	make -C ece140 clean
	make -C math115 clean
	make -C math117 clean
	make -C se101 clean
