all: cs341 cs349 sci238 se350 se465


cs341:
	make -C cs341

cs349:
	make -C cs349

sci238:
	make -C sci238

se350:
	make -C se350

se465:
	make -C se465


clean:
	make -C cs341 clean
	make -C cs349 clean
	make -C sci238 clean
	make -C se350 clean
	make -C se465 clean


.PHONY: cs341 cs349 sci238 se350 se465
