include ../latex.Makefile


all: cs343.pdf cs348.pdf earth121.pdf se380.pdf se390.pdf se464.pdf

clean:
	rm -f cs343.pdf
	rm -f cs348.pdf
	rm -f earth121.pdf
	rm -f se380.pdf
	rm -f se390.pdf
	rm -f se464.pdf
