all: cs343 cs348 earth121 se380 se390 se464


cs343:
	make -C cs343

cs348:
	make -C cs348

earth121:
	make -C earth121

se380:
	make -C se380

se390:
	make -C se390

se464:
	make -C se464


clean:
	make -C cs343 clean
	make -C cs348 clean
	make -C earth121 clean
	make -C se380 clean
	make -C se390 clean
	make -C se464 clean


.PHONY: cs343 cs348 earth121 se380 se390 se464
